const products = [
    {
        id: 0,
        title: 'Trident X Plus 9th',
        img: '/images/products/trident_x_plus_9_main.png',
        cpu_description: '9th Gen Intel® Core™ i9-9900K / i7-9700K processor',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'GeForce RTX™ 2080 Ti / 2080 Super / 2070 Super / 2070 graphics',
        gpu: 20800,
        description1: '10 liters in size, the most compact gaming desktop',
        description2: 'Silent Storm Cooling 3',
        description3: 'Support 4K gaming experience',
        description4: 'Tempered Glass Side Panel',
        description5: 'Easy upgrade',
        description6: 'Compact, light weight and easy to transport case',
        description7: 'Nahimic 3 Audio Enhancer',
        description8: 'Mystic Light RGB LED design, customize your look',
        description9: 'Enrich your experience with included MSI software',
        price: 1300,
        img1: '/images/products/trident_x_plus_9_1.png',
        img2: '/images/products/trident_x_plus_9_2.png',
        img3: '/images/products/trident_x_plus_9_3.png',
        img4: '/images/products/trident_x_plus_9_4.png',
    },

    {
        id: 1,
        title: 'Prestige P100 9th',
        img: '/images/products/prestige_p100_9_main.png',
        cpu_description: '9th Gen Intel® Core™ i9-9900K / i7-9700K processor',
        cpu: 9,
        operative_system: 'Windows 10 Pro',
        gpu_description: 'GeForce RTX™ 2080 Ti / 2080 Super / 2070 Super / 2070 graphics',
        gpu: 20800,
        description1: '10.36 liters in size, the most compact gaming desktop',
        description2: 'Silent Storm Cooling 3',
        description3: 'Accelerates the rendering task and work in real time',
        description4: 'White chassis',
        description5: 'Easy upgrade',
        description6: 'Compact, light weight and easy to transport case',
        description7: 'Nahimic 3 Audio Enhancer',
        description8: 'Mystic Light RGB LED design, customize your look',
        description9: 'Enrich your experience with included MSI software',
        price: 1700,
        img1: '/images/products/prestige_p100_9_1.png',
        img2: '/images/products/prestige_p100_9_2.png',
        img3: '/images/products/prestige_p100_9_3.png',
        img4: '/images/products/prestige_p100_9_4.png',
    },

    {
        id: 2,
        title: 'Trident X 9th',
        img: '/images/products/trident_x_9_main.png',
        cpu_description: '9th Gen Intel® Core™ i9-9900K / i7-9700K processor',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'GeForce RTX™ 2080 Ti / 2080 / 2070 graphics',
        gpu: 20800,
        description1: '10 liters in size, the most compact gaming desktop',
        description2: 'Silent Storm Cooling 3',
        description3: 'Support 4K gaming experience',
        description4: 'Tempered Glass Side Panel',
        description5: 'Easy upgrade',
        description6: 'Compact, light weight and easy to transport case',
        description7: 'Nahimic 3 Audio Enhancer',
        description8: 'Mystic Light RGB LED design, customize your look',
        description9: 'Enrich your experience with included MSI software',
        price: 1400,
        img1: '/images/products/trident_x_9_1.png',
        img2: '/images/products/trident_x_9_2.png',
        img3: '/images/products/trident_x_9_3.png',
        img4: '/images/products/trident_x_9_4.png', 
        
    },

    {
        id: 3,
        title: 'Trident 3 Artic 8th',
        img: '/images/products/trident_3_artic_8_main.png',
        cpu_description: '8th Gen Intel® Core™ i7-8700 processor with DDR4 memory',
        cpu: 8,
        operative_system: 'Windows 10 Home',
        gpu_description: 'GeForce RTX™ 2080 Ti / 2080 / 2070 graphics',
        gpu: 20800,
        description1: 'Compact, light weight and easy to transport case',
        description2: 'Full performance in extra-compact 4.72-liter case',
        description3: 'Exclusive cooling system, Silent storming cooling 2',
        description4: 'Choose to place your Gaming PC horizontally or vertically',
        description5: 'Carefully though connection ports to fit your needs as a gamer',
        description6: 'MSI Gaming Graphics Cards delivery better gaming performance',
        description7: 'Audio Boost 3: Reward your ears with studio grade sound quality',
        description8: 'Nahimic 3 Audio Enhancer',
        description9: 'Supports 4K video and 4K game',
        price: 1350,
        img1: '/images/products/trident_3_artic_8_1.png',
        img2: '/images/products/trident_3_artic_8_2.png',
        img3: '/images/products/trident_3_artic_8_3.png',
        img4: '/images/products/trident_3_artic_8_4.png', 
        
    },

    {
        id: 4,
        title: 'Trident 3 8th',
        img: '/images/products/trident_3_8_main.png',
        cpu_description: '8th Gen Intel® Core™ i7-8700 processor with DDR4 memory',
        cpu: 8,
        operative_system: 'Windows 10 Home',
        gpu_description: 'GeForce RTX™ 2080 Super / 2080 Ti / 2070 graphics',
        gpu: 20801,
        description1: 'The world‘s smallest VR ready gaming PC',
        description2: 'Accessible and ready to be upgraded in an ease',
        description3: 'Compact, light weight and easy to transport case',
        description4: 'Full performance in extra-compact 4.72-liter case',
        description5: 'Exclusive cooling system, Silent storming cooling 2',
        description6: 'Choose to place your Gaming PC horizontally or vertically',
        description7: 'Carefully though connection ports to fit your needs as a gamer',
        description8: 'MSI Gaming Graphics Cards delivery better gaming performance',
        description9: 'Audio Boost 3: Reward your ears with studio grade sound quality',
        price: 1450,
        img1: '/images/products/trident_3_8_1.png',
        img2: '/images/products/trident_3_8_2.png',
        img3: '/images/products/trident_3_8_3.png',
        img4: '/images/products/trident_3_8_4.png', 
        
    },

    {
        id: 5,
        title: 'Trident 3 8th',
        img: '/images/products/infinite_x_plus_9_main.png',
        cpu_description: '9th Gen Intel® Core™ i9 -9900K processor with DDR4 memory',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce® RTX 2080 Ti 11GB GDDR6 graphics',
        gpu: 20800,
        description1: 'Exclusive Silent Storm Cooling 3 PRO cooling system enhances system cooling and keeps it silent.',
        description2: 'Mystic Light RGB LED design to customize your Gaming PC',
        description3: 'Easy to upgrade - designed to upgrade your components with an ease.',
        description4: 'Built-in carry handle – Take your Gaming Desktop everywhere with the easy to carry handle.',
        description5: 'Vertical graphics optimal protection for your components during transport',
        description6: 'Load your games in seconds with Super RAID 4',
        description7: 'Nahimic 3.0 Audio Enhancer',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'Exclusive MSI Dragon Center',
        price: 1650,
        img1: '/images/products/infinite_x_plus_9_1.png',
        img2: '/images/products/infinite_x_plus_9_2.png',
        img3: '/images/products/infinite_x_plus_9_3.png',
        img4: '/images/products/infinite_x_plus_9_4.png', 

    },

    {
        id: 6,
        title: 'Trident 3 Artic 9th',
        img: '/images/products/trident_3_artic_9_main.png',
        cpu_description: 'Up to 9th Generation Intel® Core™ i7 processor with DDR4 memory.',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce RTX™ 2080 Super 6GB GDDR6',
        gpu: 20801,
        description1: 'Silent Storm Cooling not only cool but also silent',
        description2: 'USB Type C with reversible design',
        description3: '4.72 liters in size- the world’s smallest VR ready gaming PC',
        description4: 'Nahimic 3 Audio Enhancer',
        description5: 'Mystic Light LED design - fantastic light effect with 16.8 millions color',
        description6: 'Super Charger: super power delivery, quickly charge your mobile device',
        description7: 'Nahimic 3.0 Audio Enhancer',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'Exclusive MSI Dragon Center',
        price: 1500,
        img1: '/images/products/trident_3_artic_9_1.png',
        img2: '/images/products/trident_3_artic_9_2.png',
        img3: '/images/products/trident_3_artic_9_3.png',
        img4: '/images/products/trident_3_artic_9_4.png', 
        
    },

    {
        id: 7,
        title: 'Aegis R',
        img: '/images/products/aegis_r_main.png',
        cpu_description: 'Latest 9th Gen Intel® Core™ i7-9700 processor',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce RTX™ 1660 Ti Super 6GB GDDR6',
        gpu: 16601,
        description1: 'Easy to upgrade with standard MSI components and case',
        description2: 'Tempered glass side panel',
        description3: 'Customize your desktop with MSI LED button',
        description4: 'Nahimic 3 Audio Enhancer',
        description5: 'Exclusive MSI Dragon Center',
        description6: 'Super Charger: super power delivery, quickly charge your mobile device',
        description7: 'Nahimic 3.0 Audio Enhancer',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'Mystic Light LED design - fantastic light effect with 16.8 millions color',
        price: 1300,
        img1: '/images/products/aegis_r_1.png',
        img2: '/images/products/aegis_r_2.png',
        img3: '/images/products/aegis_r_3.png',
        img4: '/images/products/aegis_r_4.png', 
        
    },

    {
        id: 8,
        title: 'Codex R',
        img: '/images/products/codex_r_main.png',
        cpu_description: 'Up to latest 9th Gen Intel® Core™ i7-9700F processor',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to latest NVIDIA® GeForce® GTX 1660 SUPER™',
        gpu: 16602,
        description1: 'MSI’s LED Button – Unlock all RGB lighting effects to personalize your gaming RIG',
        description2: 'Latest Wi-Fi 6 (802.11ax) for redefined wireless gaming experience',
        description3: 'Easy to upgrade with standard MSI components and case',
        description4: 'High-Efficiency RGB CPU Cooler – Deliver maximum heat dissipation.',
        description5: 'MSI Z390 Motherboard - A durable high-performance motherboard made for gaming.',
        description6: 'Super Charger: super power delivery, quickly charge your mobile device',
        description7: 'Nahimic 3.0 Audio Enhancer',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'Mystic Light LED design - fantastic light effect with 16.8 millions color',
        price: 1270,
        img1: '/images/products/codex_r_1.png',
        img2: '/images/products/codex_r_2.png',
        img3: '/images/products/codex_r_3.png',
        img4: '/images/products/codex_r_4.png', 
        
    },

    {
        id: 9,
        title: 'Aegis RS',
        img: '/images/products/aegis_rs_main.png',
        cpu_description: 'Up to latest 9th Gen Intel® Core™ i7-9700KF processor',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to latest NVIDIA® GeForce® RTX 2080 Super™',
        gpu: 20801,
        description1: 'MSI’s LED Button - Customize your desktop with 60 lighting effects.',
        description2: 'Latest Wi-Fi 6 (802.11ax) for redefined wireless gaming experience',
        description3: 'Easy to upgrade with standard MSI components and case',
        description4: 'MSI Z390-A PRO - A durable high-performance motherboard made for gaming.',
        description5: '120mm Dragon CPU Liquid Cooler',
        description6: 'Mystic Light LED design - fantastic light effect with 16.8 millions color',
        description7: 'Nahimic 3.0 Audio Enhancer',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'Super Charger: super power delivery, quickly charge your mobile device',
        price: 1320,
        img1: '/images/products/aegis_rs_1.png',
        img2: '/images/products/aegis_rs_2.png',
        img3: '/images/products/aegis_rs_3.png',
        img4: '/images/products/aegis_rs_4.png', 
        
    },

    {
        id: 10,
        title: 'Codex XE Plus 9th',
        img: '/images/products/codex_xe_plus_9_main.png',
        cpu_description: 'Latest Intel® 9th Gen Processors with DDR4 Memory and Optane support',
        cpu: 9,
        operative_system: 'Windows 10 support',
        gpu_description: 'The latest MSI GeForce® RTX™ Graphics Card',
        gpu: 16600,
        description1: 'USB 3.1 Gen1 Type C with reversible design',
        description2: 'Supports NVMe PCI-E Gen3 SSD',
        description3: 'AUDIO BOOST: Reward your ears with studio grade sound quality',
        description4: 'DDR4 Boost: Incomparable memory performance and stability.',
        description5: 'VR Ready: Best virtual reality gaming experience with less motion sickness and zero latency',
        description6: 'PCI-E Steel Armor：Protecting VGA cards against bending and EMI',
        description7: 'Nahimic 3.0 Audio Enhancer',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'Super Charger: super power delivery, quickly charge your mobile device',
        price: 1320,
        img1: '/images/products/codex_xe_plus_9_1.png',
        img2: '/images/products/codex_xe_plus_9_2.png',
        img3: '/images/products/codex_xe_plus_9_3.png',
        img4: '/images/products/codex_xe_plus_9_4.png', 
        
    },

    {
        id: 11,
        title: 'Codex XE',
        img: '/images/products/codex_xe_main.png',
        cpu_description: 'Latest Intel® 9th Gen Processors with DDR4 Memory and Optane support',
        cpu: 9,
        operative_system: 'Windows 10 support',
        gpu_description: 'The latest MSI GeForce® RTX™ Graphics Card',
        gpu: 20801,
        description1: 'USB 3.1 Gen1 Type C with reversible design',
        description2: 'Supports NVMe PCI-E Gen3 SSD',
        description3: 'AUDIO BOOST: Reward your ears with studio grade sound quality',
        description4: 'DDR4 Boost: Incomparable memory performance and stability.',
        description5: 'VR Ready: Best virtual reality gaming experience with less motion sickness and zero latency',
        description6: 'PCI-E Steel Armor：Protecting VGA cards against bending and EMI',
        description7: 'Super Charger: super power delivery, quickly charge your mobile device',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'Nahimic 3.0 Audio Enhancer',
        price: 1560,
        img1: '/images/products/codex_xe_1.png',
        img2: '/images/products/codex_xe_2.png',
        img3: '/images/products/codex_xe_3.png',
        img4: '/images/products/codex_xe_4.png', 
        
    },

    {
        id: 12,
        title: 'Aegis Ti3 8th',
        img: '/images/products/aegis_t13_8_main.png',
        cpu_description: '8th Gen Intel® Core™ i7-8700K processor with DDR4 memory ',
        cpu: 8,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce GTX 1660 Ti GAMING 8GB GDDR5X graphics in SLI',
        gpu: 16601,
        description1: 'Unlimited speed gaming storage card (optional)',
        description2: '16GB Intel® Optane™ memory included: Boost your system up to 14X faster',
        description3: 'VR Ready with VR Link; ‘One-Click-VR‘ and HDMI out port',
        description4: 'Exclusive Silent Storm Cooling 3 Pro cooling system with liquid cooling',
        description5: 'Game Boost button to quickly enhance system performance',
        description6: 'Compact case with built-in carry handle',
        description7: 'Easy to access and upgrade',
        description8: 'Mystic Light RGB LED design to customize your Gaming PC',
        description9: 'Get the best online experience with Killer LAN',
        price: 1440,
        img1: '/images/products/aegis_t13_8_1.png',
        img2: '/images/products/aegis_t13_8_1.png',
        img3: '/images/products/aegis_t13_8_1.png',
        img4: '/images/products/aegis_t13_8_1.png', 
        
    },

    {
        id: 13,
        title: 'Trident 3 9th',
        img: '/images/products/trident_3_8_main.png',
        cpu_description: 'Up to 9th Generation Intel® Core™ i7 processor with DDR4 memory.',
        cpu: 9,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce RTX™ 1660 Super 6GB GDDR6',
        gpu: 16602,
        description1: 'Silent Storm Cooling not only cool but also silent',
        description2: 'USB Type C with reversible design',
        description3: '4.72 liters in size- the worlds smallest VR ready gaming PC',
        description4: 'Nahimic 3 Audio Enhancer',
        description5: 'Mystic Light LED design - fantastic light effect with 16.8 millions color',
        description6: 'Super Charger: super power delivery, quickly charge your mobile device.',
        description7: 'Easy to access and upgrade',
        description8: 'Mystic Light RGB LED design to customize your Gaming PC',
        description9: 'Get the best online experience with Killer LAN',
        price: 1810,
        img1: '/images/products/trident_3_8_1.png',
        img2: '/images/products/trident_3_8_2.png',
        img3: '/images/products/trident_3_8_3.png',
        img4: '/images/products/trident_3_8_4.png', 
        
    },

    {
        id: 14,
        title: 'Aegis 3 Plus 10th',
        img: '/images/products/aegis_3_plus_8_main.png',
        cpu_description: '10th Gen Intel® Core™ i7 -8700 processor with DDR4 memory and Optane support',
        cpu: 10,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce® GTX 2080 Super 8GB GDDR5 graphics',
        gpu: 20801,
        description1: 'Optional 16GB Intel® Optane™ memory: Boost your system storage up to 14X faster',
        description2: 'Exclusive Silent Storm Cooling 2 cooling system',
        description3: 'Compact case with built-in carry handle',
        description4: 'Vertical graphics optimal protection for your components during transport',
        description5: 'Easy to access and upgrade',
        description6: 'Mystic Light RGB LED design to customize your Gaming PC',
        description7: 'Audio Boost 3: Reward your ears with studio grade sound quality',
        description8: 'Nahimic 3 Audio Enhancer',
        description9: 'Supports NVMe PCI-E Gen3 SSD speed up to 2.2GB/s',
        price: 1810,
        img1: '/images/products/aegis_3_plus_8_1.png',
        img2: '/images/products/aegis_3_plus_8_2.png',
        img3: '/images/products/aegis_3_plus_8_3.png',
        img4: '/images/products/aegis_3_plus_8_4.png', 
        
    },

    {
        id: 15,
        title: 'Infinite X',
        img: '/images/products/infinite_x_main.png',
        cpu_description: '10th Gen Intel® Core™ i7 -8700K processor with DDR4 memory',
        cpu: 10,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce GTX 2080 Ti 11GB GDDR5X graphics',
        gpu: 20800,
        description1: 'Exclusive Silent Storm Cooling 3 PRO cooling system enhances system cooling and keeps it silent.',
        description2: 'Mystic Light RGB LED design to customize your Gaming PC',
        description3: 'Easy to upgrade - designed to upgrade your components with an ease.',
        description4: 'Built-in carry handle – Take your Gaming Desktop everywhere with the easy to carry handle.',
        description5: 'Vertical graphics optimal protection for your components during transport',
        description6: 'Load your games in seconds with Super RAID 4',
        description7: 'PCIe Steel Armor - Prevent the PCIe slot from breaking.',
        description8: 'Nahimic 2.0+ Audio Enhancer',
        description9: 'Audio Boost: Reward your ears with studio grade sound quality',
        price: 1810,
        img1: '/images/products/infinite_x_1.png',
        img2: '/images/products/infinite_x_2.png',
        img3: '/images/products/infinite_x_3.png',
        img4: '/images/products/infinite_x_4.png', 
        
    },

    {
        id: 16,
        title: 'Infinite A 10th',
        img: '/images/products/infinite_a_8_main.png',
        cpu_description: '10th Gen Intel® Core™ i7-8700 processor with DDR4 memory',
        cpu: 10,
        operative_system: 'Windows 10 Home',
        gpu_description: 'Up to MSI GeForce® GTX 1070 Ti 8GB GDDR5 graphics',
        gpu: 16602,
        description1: 'Supports Intel® Optane™ memory: Boost your system up to 14X faster',
        description2: 'Exclusive Silent Storm Cooling 3 cooling system enhances system cooling and keeps it silent.',
        description3: 'Mystic Light RGB LED design to customize your Gaming PC',
        description4: 'Easy to upgrade - designed to upgrade your components with an ease.',
        description5: 'Built-in carry handle – Take your Gaming Desktop everywhere with the easy to carry handle.',
        description6: 'Vertical graphics optimal protection for your components during transport',
        description7: 'Nahimic 3+ Audio Enhancer',
        description8: 'Audio Boost: Reward your ears with studio grade sound quality',
        description9: 'High quality and durable components Military Class 5',
        price: 1810,
        img1: '/images/products/infinite_a_8_1.png',
        img2: '/images/products/infinite_a_8_2.png',
        img3: '/images/products/infinite_a_8_3.png',
        img4: '/images/products/infinite_a_8_4.png', 
        
    },

    {
        id: 17,
        title: 'Cubi 3 Silent S',
        img: '/images/products/cubi_3_silent_s_main.png',
        cpu_description: 'Intel® Kabylake-U processor',
        cpu: 7,
        operative_system: 'Windows 10 Home - MSI recommends Windows 10 Pro',
        gpu_description: 'Up to MSI GeForce® GTX 1660 8GB GDDR5 graphics',
        gpu: 16600,
        description1: 'DDR4 2133MHz up to 32GB (2 Slots)',
        description2: 'The fanless design extends the product life cycle and reduces the dust into the product',
        description3: 'Supports 4K ultra-high definition resolution',
        description4: 'Supports dual monitors',
        description5: 'Supports M.2 SATA/PCI-e auto switch SSD or 2.5” SATAIII HDD or SS',
        description6: 'Equipped Complete IO',
        description7: 'Supports super charger',
        description8: 'Power delivered by USB in the Off state',
        description9: 'Embedded Software TPM and supports Hardware TPM modul',
        price: 1000,
        img1: '/images/products/cubi_3_silent_s_1.png',
        img2: '/images/products/cubi_3_silent_s_2.png',
        img3: '/images/products/cubi_3_silent_s_3.png',
        img4: '/images/products/cubi_3_silent_s_4.png', 
        
    },

    {
        id: 18,
        title: 'Cubi N',
        img: '/images/products/cubi_in_main.png',
        cpu_description: 'Intel® Braswell N Processor',
        cpu: 7,
        operative_system: 'Windows 10 Pro',
        gpu_description: 'Up to MSI GeForce® GTX 1660 Ti 8GB GDDR5 graphics',
        gpu: 16601,
        description1: 'SupportsDDR3L 1600MHz up to 8GB',
        description2: 'Intel® Braswell N Processor',
        description3: 'Only 0.45L liters',
        description4: 'Supports Maximum to 1 x mSATA SSD and 1 x 2.5” SATA HDD (with extension bay)',
        description5: 'Maximum to 1 x mSATA SSD and 1 x 2.5” SATA HDD (with extension bay)',
        description6: '802.11ac Combo Card',
        description7: 'Fan-less design',
        description8: 'Support standard VESA-mount',
        description9: 'Embedded Software TPM and supports Hardware TPM modul',
        price: 1000,
        img1: '/images/products/cubi_in_1.png',
        img2: '/images/products/cubi_in_1.png',
        img3: '/images/products/cubi_in_1.png',
        img4: '/images/products/cubi_in_1.png', 
        
    },

    {
        id: 19,
        title: 'Cubi 5 10M',
        img: '/images/products/cubi_5_10m_main.png',
        cpu_description: 'Up to 7th Gen. Intel® Core™ i7 U-Processor',
        cpu: 7,
        operative_system: 'Windows 10 Home - MSI recommends Windows 10 Pro',
        gpu_description: 'Up to MSI GeForce® GTX 1660 Super 8GB GDDR5 graphics',
        gpu: 16602,
        description1: 'Supports Wifi 6',
        description2: 'Intel® Braswell N Processor',
        description3: 'Equipped with USB 3.2 Gen1 type C',
        description4: 'Maximum to 1 x M.2 SSD and 1 x 2.5” SSD/HDD',
        description5: 'Supports Dual monitors',
        description6: '802.11ac Combo Card',
        description7: 'Fan-less design',
        description8: 'Support standard VESA-mount',
        description9: 'Supports standard VESA-mount',
        price: 1170,
        img1: '/images/products/cubi_5_10m_1.png',
        img2: '/images/products/cubi_5_10m_2.png',
        img3: '/images/products/cubi_5_10m_3.png',
        img4: '/images/products/cubi_5_10m_4.png', 
        
    },
];

module.exports = products;